default_platform(:ios)

mac_config = {
  app_identifier: 'com.fespinozacast.LinkedIdeas',
  scheme: 'LinkedIdeas',
  workspace: 'LinkedIdeas.xcworkspace',
  appstore: {
    configuration: 'Release'
  }
}

ios_config = {
  app_identifier: 'com.fespinozacast.New-LinkedIdeas-iOS',
  scheme: 'LinkedIdeas-iOS',
  workspace: 'LinkedIdeas.xcworkspace',
  appstore: {
    configuration: 'Release'
  }
}

platform :mac do
  lane :test do
    xcode_select('/Applications/Xcode-beta.app')
    run_tests(scheme: 'LinkedIdeas')
  end

  desc 'Push a new release build to the Mac App Store'
  lane :release do
    # increment_build_number
    # commit_version_bump
    build_app(
      workspace: mac_config[:app_identifier],
      scheme: mac_config[:scheme],
      configuration: mac_config[:appstore][:configuration],
      include_bitcode: true
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end

platform :ios do
  lane :test do
    xcode_select('/Applications/Xcode-beta.app')
    sync_code_signing(
      type: 'development',
      app_identifier: ios_config[:app_identifier]
    )
    run_tests(scheme: ios_config[:scheme])
  end

  desc 'Push a new release build to the App Store'
  lane :release do
    increment_build_number
    commit_version_bump
    sync_code_signing(
      type: 'appstore',
      app_identifier: ios_config[:app_identifier]
    )
    build_app(
      workspace: ios_config[:workspace],
      scheme: ios_config[:scheme],
      configuration: ios_config[:appstore][:configuration],
      include_bitcode: true
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
